ci: avoid uploading duplicate wheels artifacts
actions/upload-artifact doesn't detect duplicate artifacts with
`archive: false` (where the artifact name is taken from the filename).
This can cause multiple artifacts with the same name to be uploaded.  To
avoid this, check whether an artifact with the wheel name exists and
skip uploading when it does.

Signed-off-by: Kevin Locke <kevin@kevinlocke.name>

diff --git a/.github/workflows/tox.yml b/.github/workflows/tox.yml
--- a/.github/workflows/tox.yml
+++ b/.github/workflows/tox.yml
@@ -114,7 +114,33 @@ jobs:
       run: ${{ matrix.python.exe }} -m tox -e ${{ matrix.python.toxenv }}
     - name: Build sdist and wheel
       run: python -m build
+    - name: Check whether wheel artifact already exists
+      id: wheel_artifact
+      env:
+        GH_TOKEN: ${{ github.token }}
+      shell: bash
+      run: |
+        wheels=( dist/*.whl )
+        if [ "${#wheels[@]}" -ne 1 ]; then
+          echo "::error::Expected 1 wheel, got ${#wheels[@]}: ${wheels[*]}"
+          exit 1
+        fi
+
+        wheel=${wheels[0]}
+        wheel=${wheel#dist/}
+        if gh api \
+            "repos/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID/artifacts" \
+            --jq '.artifacts.[].name' |
+          grep -Fxq "$wheel"; then
+          echo 'exists=true' >"$GITHUB_OUTPUT"
+        else
+          echo 'exists=false' >"$GITHUB_OUTPUT"
+        fi
     - name: Archive wheel
+      # upload-artifact overwrite doesn't handle archive: false:
+      # https://github.com/actions/upload-artifact/issues/769
+      # to avoid duplicate artifacts, skip upload when it already exists
+      if: steps.wheel_artifact.outputs.exists == false
       uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a  # v7.0.1
       with:
         path: dist/*.whl
